"""remove subject from attendance

Revision ID: b8d1a1a69853
Revises: ae7753d988aa
Create Date: 2026-09-01 18:49:01.532759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d1a1a69853'
down_revision = 'ae7753d988aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('attendance_subject_id_fkey'), type_='foreignkey')
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('attendance_subject_id_fkey'), 'subjects', ['subject_id'], ['id'])

    # ### end Alembic commands ###
